/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    public void testRandomQuote() throws IOException {
        QuoteManager quoteManager = new QuoteManager("src/main/resources/recentquotes.json");
        Quote randomQuote = quoteManager.getRandomQuote();

        assertNotNull(randomQuote);
        assertNotNull(randomQuote.getText());
        assertNotNull(randomQuote.getAuthor());
    }
}
