/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import java.io.IOException;

public class App {


    public static void main(String[] args) {
        try {
            QuoteManager quoteManager = new QuoteManager("src/main/resources/recentquotes.json");
            Quote randomQuote = quoteManager.getRandomQuote();
            System.out.println("Quote: " + randomQuote.getText());
            System.out.println("Author: " + randomQuote.getAuthor());
        } catch (IOException e) {
            System.err.println("Error reading JSON file: " + e.getMessage());
        }
    }
    }
